### ISSUE TITLE
On uwsgi errors (not sure which), NGINX closes uwsgi's socket.

### ISSUE THREAD

**Issue by huevosabio** [huevosabio/windopt#35]
This behavior then makes it impossible for NGINX to write any request to uwsgi, and breaks the entire app.

**Comment by huevosabio** [comment]
So what we have is

```
2016/01/22 14:39:40 [error] 15#0: *199 upstream prematurely closed connection while reading response header from upstream, client: 172.17.42.1, server: windops.com, reque
st: "POST /api/auth/login HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock:", host: "wind_server", referrer: "http://wind.ramondario.com/wind
day"
```
and then
```
2016/01/22 15:26:34 [error] 12#0: *283 upstream timed out (110: Connection timed out) while sending request to upstream, client: 172.17.42.1, server: windops.com, request
: "POST /api/windyday/Fowler/upload HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock", host: "wind_server", referrer: "http://wind.ramondario
.com/"
```

**Comment by huevosabio** [comment]
I'm looking at the nginx again, and I find a patern:

```
rio.com/"
2016/01/22 14:38:25 [error] 15#0: *195 upstream prematurely closed connection while reading response header from upstream, client: 172.17.42.1, server: windops.com, reque
st: "POST /api/auth/login HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock:", host: "wind_server", referrer: "http://wind.ramondario.com/wind
day"
2016/01/22 14:38:27 [error] 15#0: *197 upstream prematurely closed connection while reading response header from upstream, client: 172.17.42.1, server: windops.com, reque
st: "POST /api/auth/login HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock:", host: "wind_server", referrer: "http://wind.ramondario.com/wind
day"
2016/01/22 14:39:40 [error] 15#0: *199 upstream prematurely closed connection while reading response header from upstream, client: 172.17.42.1, server: windops.com, reque
st: "POST /api/auth/login HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock:", host: "wind_server", referrer: "http://wind.ramondario.com/wind
day"
2016/01/22 15:26:34 [error] 12#0: *283 upstream timed out (110: Connection timed out) while sending request to upstream, client: 172.17.42.1, server: windops.com, request
: "POST /api/windyday/Fowler/upload HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock", host: "wind_server", referrer: "http://wind.ramondario
.com/"
2016/01/22 15:26:48 [error] 12#0: *285 upstream timed out (110: Connection timed out) while sending request to upstream, client: 172.17.42.1, server: windops.com, request
: "POST /api/windyday/Fowler/upload HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock", host: "wind_server", referrer: "http://wind.ramondario
.com/"
2016/01/22 15:27:33 [error] 12#0: *292 upstream timed out (110: Connection timed out) while sending request to upstream, client: 172.17.42.1, server: windops.com, request
: "POST /api/windyday/Fowler/upload HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock", host: "wind_server", referrer: "http://wind.ramondario
.com/"
2016/01/22 15:31:01 [error] 12#0: *329 upstream timed out (110: Connection timed out) while sending request to upstream, client: 172.17.42.1, server: windops.com, request
: "POST /api/windyday/Fowler/upload HTTP/1.1", upstream: "uwsgi://unix:/var/www/windopt/config/windopt_uwsgi.sock", host: "wind_server", referrer: "http://wind.ramondar
~            
```

apparently, the previous errors, although not to be ignored, were generally harmless: the machinery kept moving. We can see this because we have endless of those before the snippet shown here. But then we see 4 messages with "upstream timed out". We also have 4 uwsgi processes. This means that something in the POST "/api/windyday/<project>/upload" is breaking the uwsgi process. After considerable Googling I find this [here](http://monicalent.com/blog/2013/12/06/set-up-nginx-and-uwsgi/): 
```
"limit-as Unix has some sort of built in limits for what it can transfer. You may need to set this value if you get errors such as"
```

I've added the limit-as option to the uwsgi ini file and set it to 1024 (MB). I'm in the process of testing.

**Comment by huevosabio** [comment]
I've narrowed the issue. Indeed there was an issue, basically Flask was producing this: 

```python
Traceback (most recent call last):
  File "/home/ramon/development/windopt/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ramon/development/windopt/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ramon/development/windopt/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ramon/development/windopt/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ramon/development/windopt/venv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/ramon/development/windopt/venv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

Which in turn crashed the uwsgi process. This was made because I had a logic with 
```python
if condition:
    # code
    return jsonify(some_dict)
```

But this never specifies what happens if the condition is not met, obviously Flask throws an error that breaks the whole thing. I will skim through current implemented routes for similar code.

**Comment by huevosabio** [comment]
Not solved. After building the whole stack with docker, it basically does nothing. Not respond, not anything. I'm going to sleep and tackle this with a fresh mind tomorrow.

**Comment by huevosabio** [comment]
This has been solved, did by reducing the uwsgi_read_timeout to 300s, not sure how any of that works...

**Comment by huevosabio** [comment]
Actually... the realy solution was to add this to the *host* server's nginx's server conf:

```
proxy_set_header Connection "";
```

and 

```
keepalive 100;
```

for the same on but in the upstream conf
